# CodeRabbit Configuration for Memento MCP Server (Cloudflare Workers)
# https://docs.coderabbit.ai/configuration/
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US

tone_instructions: |
  This is Claude's experiential memory system - the MCP server that gives Claude persistent memory across sessions. Focus on correctness: MCP protocol compliance, Neo4j query accuracy, async error handling, OAuth security. Be direct and technical.

early_access: true

reviews:
  profile: assertive

  request_changes_workflow: true

  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'

  poem: false

  review_status: true

  collapse_walkthrough: false

  sequence_diagrams: true

  changed_files_summary: true

  path_filters:
    - '!**/node_modules/**'
    - '!**/.wrangler/**'
    - '!**/dist/**'

  path_instructions:
    #---------------------------------------------------------------------------
    # MCP TOOL IMPLEMENTATIONS
    #---------------------------------------------------------------------------
    - path: 'src/tools/**/*.ts'
      instructions: |
        ## MCP Tool Implementation Review

        **Context:** These are MCP (Model Context Protocol) tools that Claude uses to read/write its experiential memory. The memory persists in Neo4j Aura (graph database).

        **MCP Protocol Requirements:**
        - All tools must return `{ content: [{ type: 'text', text: string }] }`
        - Error responses must include `isError: true`
        - Tool schemas use Zod for validation

        **Neo4j Query Patterns:**
        - Entities use soft-delete via `validTo` field (null = current, timestamp = deleted)
        - Always filter `WHERE e.validTo IS NULL` for current entities
        - Observations are stored as JSON strings, parsed client-side
        - Embeddings are 1024-dimension float arrays (VoyageAI voyage-3-lite)

        **Error Handling:**
        - All async operations must be try/catch wrapped
        - Errors should be caught and returned as MCP error responses
        - Never throw unhandled - Workers will crash

        **Acceptable Patterns (don't flag):**
        - Use of `any` type for Neo4j query results (dynamic schema)
        - console.error for logging (Workers standard)
        - JSON.stringify for response formatting

    #---------------------------------------------------------------------------
    # SEMANTIC SEARCH (Gannon's RRF Implementation)
    #---------------------------------------------------------------------------
    - path: 'src/semantic-search.ts'
      instructions: |
        ## Semantic Search Review

        **Context:** This implements hybrid Reciprocal Rank Fusion (RRF) search combining vector similarity with BM25-style keyword matching. This is "Gannon's kung fu" - ported from the original Memento implementation.

        **RRF Algorithm:**
        - Formula: score = 1 / (k + rank + 1), where k=60
        - Items appearing in BOTH vector and keyword results get scores SUMMED
        - This is the "context-aware" magic - semantic + exact matching

        **Vector Search:**
        - Uses Neo4j's native vector index: `db.index.vector.queryNodes`
        - Index name: 'entity_embeddings'
        - Embedding dimension: 1024 (VoyageAI voyage-3-lite)

        **Keyword Search:**
        - Searches entity names (2.0x boost) and observations (0.5 per match)
        - Observations stored as JSON arrays in Neo4j

        **Don't flag:**
        - The RRF constant k=60 (standard value, intentional)
        - Fetching 2x candidates for RRF merging (intentional over-fetch)

    #---------------------------------------------------------------------------
    # NEO4J HTTP CLIENT
    #---------------------------------------------------------------------------
    - path: 'src/neo4j-client.ts'
      instructions: |
        ## Neo4j HTTP Client Review

        **Context:** This uses Neo4j's HTTP Query API v2 (not Bolt driver) because Cloudflare Workers can't use TCP sockets.

        **API Endpoint:**
        - POST to `{uri}/db/neo4j/query/v2`
        - Auth: Basic auth header with user:password
        - Request body: `{ statement: string, parameters?: object }`

        **Response Handling:**
        - API returns `{ data: { fields: [], values: [[]] } }`
        - Must transform to array of objects using fields as keys

        **Security:**
        - Credentials come from Cloudflare secrets (env bindings)
        - Never log credentials or include in error messages

    #---------------------------------------------------------------------------
    # EMBEDDING SERVICE
    #---------------------------------------------------------------------------
    - path: 'src/embedding-service.ts'
      instructions: |
        ## VoyageAI Embedding Service Review

        **Context:** Generates 1024-dimension embeddings for semantic search.

        **API:**
        - Model: voyage-3-lite
        - Endpoint: https://api.voyageai.com/v1/embeddings
        - Input type: document (for entities being stored)

        **Error Handling:**
        - API failures should not crash entity creation
        - Consider retry logic for transient failures

    #---------------------------------------------------------------------------
    # OAUTH AUTHENTICATION
    #---------------------------------------------------------------------------
    - path: 'src/auth/**/*.ts'
      instructions: |
        ## OAuth Flow Review

        **Context:** GitHub OAuth for authenticating Claude desktop/browser access to Memento.

        **Security Critical:**
        - State parameter must be cryptographically random
        - State must be verified on callback
        - Access tokens must be stored securely (KV with encryption)
        - Never expose tokens in URLs or logs

        **Cookie Security:**
        - HttpOnly, Secure, SameSite=Lax
        - Encryption key from Cloudflare secrets

    #---------------------------------------------------------------------------
    # MAIN ENTRY POINT
    #---------------------------------------------------------------------------
    - path: 'src/index.ts'
      instructions: |
        ## Worker Entry Point Review

        **Context:** This is the Cloudflare Worker entry point using the workers-mcp framework.

        **Check for:**
        - Proper Durable Object bindings
        - Correct OAuth provider setup
        - Transport configuration (SSE + streamable HTTP)

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: auto
  issues:
    scope: auto
  opt_out: false
